name: 'Continuous Delivery'

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-image-name:latest

      - name: Deploy to GCP
        run: |
          # Aquí puedes usar gcloud para desplegar tu imagen en Cloud Run
          gcloud run deploy your-service-name \
            --image gcr.io/your-project-id/your-image-name:latest \
            --platform managed \
            --region your-region \
            --allow-unauthenticated